SELECT KRADEZ.MISTO, KRADEZ.DATUM, KRADEZ.POZN, VOZIDLO.REGISTRACE, SPZ.CISLO FROM KRADEZ
INNER JOIN KRADEZ.VOZIDLO = VOZIDLO.VIN
INNER JOIN KRADEZ.VOZIDLO = SPZ.VOZIDLO
WHERE SPZ.PRIDELENA_DO IS NULL
ORDER BY KRADEZ.DATUM DESC;