#ifndef __ADDR_SPACE__
#define __ADDR_SPACE__ 

#define FPGA_ADDR_FRAME  0
#define FPGA_ADDR_THRESHOLD  1
#define FPGA_ADDR_HISTOGRAM_WR_DONE  10
#define FPGA_ADDR_THRESHOLD_WR_DONE  11
#define FPGA_ADDR_HISTOGRAM_BASE  2
#define FPGA_ADDR_HISTOGRAM_1  (FPGA_ADDR_HISTOGRAM_BASE+0)
#define FPGA_ADDR_HISTOGRAM_2  (FPGA_ADDR_HISTOGRAM_BASE+1)
#define FPGA_ADDR_HISTOGRAM_3  (FPGA_ADDR_HISTOGRAM_BASE+2)
#define FPGA_ADDR_HISTOGRAM_4  (FPGA_ADDR_HISTOGRAM_BASE+3)
#define FPGA_ADDR_HISTOGRAM_5  (FPGA_ADDR_HISTOGRAM_BASE+4)
#define FPGA_ADDR_HISTOGRAM_6  (FPGA_ADDR_HISTOGRAM_BASE+5)
#define FPGA_ADDR_HISTOGRAM_7  (FPGA_ADDR_HISTOGRAM_BASE+6)
#define FPGA_ADDR_HISTOGRAM_8  (FPGA_ADDR_HISTOGRAM_BASE+7)

#endif
